package helper

// Generated by https://quicktype.io

type Response struct {
	Status  int64       `json:"status"`
	Message string      `json:"message"`
	Error   interface{} `json:"error"`
	Data    interface{} `json:"data"`
}

// EmptyObj used for when we don't want data returned null value
type EmptyObj struct{}

func BuildResponse(statusCode int64, message string, data interface{}) Response {
	res := Response{Status: int64(statusCode), Message: message, Error: nil, Data: data}
	return res
}

func BuildError(statusCode int64, message string, err string) Response {
	// splitErr := strings.Split(err, "/n")
	res := Response{Status: int64(statusCode), Message: message, Error: err, Data: nil}
	return res
}
